# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160530_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='placementhits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 5, 30, 12, 35, 47, 326000))),
            ],
        ),
        migrations.RemoveField(
            model_name='placement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='session',
        ),
        migrations.AddField(
            model_name='placementhits',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.placement'),
        ),
    ]
