# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160530_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placementhits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 12, 42, 9, 519000)),
        ),
    ]
