# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160530_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementhits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 12, 48, 41, 309000)),
        ),
    ]
