# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20160530_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementhits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 12, 51, 13, 664000)),
        ),
        migrations.AlterField(
            model_name='placementhits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
