# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20160530_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissionhits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 5, 30, 12, 55, 2, 866000))),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placementhits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 12, 55, 2, 869000)),
        ),
        migrations.AddField(
            model_name='admissionhits',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.admission'),
        ),
    ]
