# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160530_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionhits',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='placementhits',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
