# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20160530_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_choice', models.CharField(choices=[('Hostel C', 'Hostel C'), ('Hostel B', 'Hostel B'), ('Hostel A', 'Hostel A'), ('Hostel J', 'Hostel J'), ('Hostel H', 'Hostel H'), ('Hostel PG', 'Hostel PG'), ('Hostel I', 'Hostel I'), ('Hostel G', 'Hostel G'), ('Hostel E', 'Hostel E'), ('Other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='posts.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hostelhits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40, null=True)),
                ('created', models.DateTimeField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.hostel')),
            ],
        ),
    ]
