# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_acad_acadhits_other_otherhits_soc_sochits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionhits',
            name='session',
        ),
    ]
