# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_admissionhits_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acadhits',
            name='session',
        ),
        migrations.RemoveField(
            model_name='hostelhits',
            name='session',
        ),
        migrations.RemoveField(
            model_name='otherhits',
            name='session',
        ),
        migrations.RemoveField(
            model_name='placementhits',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sochits',
            name='session',
        ),
    ]
