# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20160606_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acadhits',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='admissionhits',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='hostelhits',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='otherhits',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='placementhits',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='sochits',
            name='ip',
        ),
        migrations.AddField(
            model_name='acadhits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='admissionhits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='hostelhits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='otherhits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='placementhits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sochits',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
