# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20160602_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterplc',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.placement_Answer'),
        ),
    ]
